apiVersion: v1
kind: Service
metadata:
  name: svc-pod-expose
  namespace: k8s-sandbox
  labels:
    app: k8s-app
    author: MSA
    type: k8s-service-lb
spec:
  selector:
    type: k8s-pod
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: flask-app
    port: 80
    targetPort: 5000
  # - name : nginx-fe
  #   port: 80
  #   targetPort: 80