apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bcapp-deploy
  namespace: mayur
  labels:
    app: k8s-app
    language: python3
    author: MSA
    type: k8s-deploy
spec:
  selector:
    matchLabels:
      app: k8s-app
      author: MSA
      type: k8s-pod-deploy
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-app
        author: MSA
        type: k8s-pod-deploy
    spec:
      containers:
      - name: bc-sandbox
        image: msa1999/k8s-sandbox:1
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 5000
          name:  flask-app